schema:
  provider: fs
  kwargs:
    file: /etc/dpch/schema.json

auth:
  provider: mock
  kwargs:
    clickhouse: &ch
      host: clickhouse
      port: 8123
      user: default
      password: "s3cur3"
      database: "default"
    secret_key: "a-super-secret-key"

executor:
  provider: dummy_clickhouse
  kwargs:
    clickhouse: *ch

debug: true