schema:
  provider: fs
  file: /etc/dpch/schema.json

auth:
  provider: mock
  clickhouse: &ch
    host: clickhouse
    port: 8123
    user: default
    password: "s3cur3"
    database: "default"
  secret_key: "a-super-secret-key"

executor:
  provider: dummy_clickhouse
  clickhouse: *ch

debug: true