version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: dp-server-dev
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:cached
      - ../example_configs:/etc/dpch
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - clickhouse
    command: ["bash", "-c", "while true; do sleep 1000; done"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-dev
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data-dev:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - "CLICKHOUSE_USER=default"
      - "CLICKHOUSE_PASSWORD=s3cur3"

volumes:
  clickhouse-data-dev:
